version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing 
  build:
    commands:
      - echo installing npm dependancies
      - npm install 
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  files:
    - '*'
    